# Chart values for the Camunda Platform 8 Helm chart in separate ingress setup.
# Note: you can change the global.image.tag version value as needed.
global:
  image:
    tag: 8.6.0-alpha1
    pullSecrets:
      - name: dev-c8-registry
  postgresql:
    auth:
      password: SetThisToMakeHelmUpgradesEasy
  
# Reduce Zeebe and Gateway replicas and resources to make it run locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 8Gi
  debug: true
  env:
    - name: LOGGING_LEVEL_IO_CAMUNDA_ZEEBE
      value: DEBUG
  
zeebeGateway:
  replicas: 1
  env:
    - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
      value: none
    - name: LOGGING_LEVEL_IO_CAMUNDA_GATEWAY
      value: DEBUG

operate:
  env:
    - name: LOGGING_LEVEL_IO_CAMUNDA_OPERATE
      value: DEBUG
  
tasklist:
  env:
    - name: LOGGING_LEVEL_IO_CAMUNDA_TASKLIST
      value: DEBUG

optimize:
  env:
    - name: LOGGING_LEVEL_IO_CAMUNDA_OPTIMIZE

connectors:
  env:
    - name: LOGGING_LEVEL_IO_CAMUNDA_CONNECTOR
  
identity:
  fullURL: "https://identity.c8.dev.local"
  env:
    - name: IDENTITY_LOG_LEVEL
      value: DEBUG

identityPostgresql:
  enabled: true

identityKeycloak:
  enabled: true
  postgresql:
    enabled: true
  extraEnvVars:
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_LOGLEVEL
      value: DEBUG
    - name: KC_LOG_LEVEL
      value: DEBUG
  auth:
    adminPassword: SetThisToMakeLoginEasy
    managementPassword: SetThisToMakeLoginEasy

 
webModeler:
  enabled: true
  restapi:
    mail:
      # Restapi.mail.smtpHost defines the host name of the SMTP server to be used by Web Modeler
      smtpHost: ""
      # Restapi.mail.smtpPort defines the port number of the SMTP server
      smtpPort: 587
      # Restapi.mail.smtpUser can be used to provide a user for the SMTP server
      smtpUser: ""
      # Restapi.mail.smtpPassword can be used to provide a password for the SMTP server
      smtpPassword: ""
      # Restapi.mail.smtpTlsEnabled if true, enforces TLS encryption for SMTP connections (using STARTTLS)
      smtpTlsEnabled: true
      # Restapi.mail.fromAddress defines the email address that will be displayed as the sender of emails sent by Web Modeler
      fromAddress: "no-reply@camunda.com"
      # Restapi.mail.fromName defines the name that will be displayed as the sender of emails sent by Web Modeler
      fromName: "Camunda Platform"
    env:
      - name: ZEEBE_INSECURE_CONNECTION
        value: "true"
      - name: ZEEBE_CA_CERTIFICATE_PATH
        value: "/home/runner/dev.c8.separated.crt"
      - name: LOGGING_LEVEL_IO_GRPC
        value: TRACE
      - name: LOGGING_LEVEL_IO_CAMUNDA_MODELER
        trace: DEBUG
    extraVolumes:
      - name: dev-c8-separated-tls
        secret:
          secretName: dev-c8-separated-tls
    extraVolumeMounts:
      - name: dev-c8-separated-tls
        mountPath: "/home/runner/dev.c8.separated.crt"
        subPath: tls.crt
  webapp:
    env:
      - name: ZEEBE_SECURE_CONNECTION
        value: "false"
      - name: ZEEBE_CLIENT_SSL_ROOT_CERTS_PATH
        value: "/home/runner/dev.c8.separated.crt"
      - name: LOGGING_LEVEL_IO_GRPC
        value: TRACE
      - name: LOGGING_LEVEL_IO_CAMUNDA_MODELER
        trace: DEBUG
    extraVolumes:
      - name: dev-c8-separated-tls
        secret:
          secretName: dev-c8-separated-tls
    extraVolumeMounts:
      - name: dev-c8-separated-tls
        mountPath: "/home/runner/dev.c8.separated.crt"
        subPath: tls.crt

postgresql:
  enabled: true
 
# Reduce Elasticsearch replicas and resources to make it run locally
elasticsearch:
#  imageTag: 7.17.3  # Uncomment this line and set a value if you want to override the default chart value.
  master:
    replicaCount: 1
