# Chart values for the Camunda Platform 8 Helm chart in separate ingress setup. 
# Note: you can change the global.image.tag version value as needed.
global:
  image:
    tag: 8.3.2
 
  ingress:
    enabled: true
    host: "c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-combined-tls"
 
  identity:
    auth:
      publicIssuerUrl: "https://c8.dev.local/auth/realms/camunda-platform"
      operate:
        existingSecret: SetThisToMakeHelmUpgradesEasy
        redirectUrl: "https://c8.dev.local/operate"
      tasklist:
        existingSecret: SetThisToMakeHelmUpgradesEasy
        redirectUrl: "https://c8.dev.local/tasklist"
      optimize:
        existingSecret: SetThisToMakeHelmUpgradesEasy
        redirectUrl: "https://c8.dev.local/optimize"
 
# Reduce Zeebe and Gateway replicas and resources to make it run locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 8Gi
 
zeebe-gateway:
  replicas: 1
  ingress:
    enabled: true
    host: "zeebe.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-combined-tls"
 
operate:
  contextPath: "/operate"
 
tasklist:
  contextPath: "/tasklist"
 
optimize:
  contextPath: "/optimize"
 
identity:
  fullURL: "https://c8.dev.local/identity"
  contextPath: "/identity"
  keycloak:
    auth:
      adminPassword: SetThisToMakeLoginEasy
      managementPassword: SetThisToMakeLoginEasy
    postgresql:
      auth:
        password: SetThisToMakeLoginEasy

# Reduce Elasticsearch replicas and resources to make it run locally
elasticsearch:
#  imageTag: 7.17.3  # Uncomment this line and set a value if you want to override the default chart value.
  master:
    replicaCount: 1