grafana:
  ingress:
    enabled: true
    hosts: 
      - grafana.c8.dev.local
    ingressClassName: nginx

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: 
      - prometheus.c8.dev.local
  prometheusSpec:
    #below line automatically adds all service monitors
    serviceMonitorSelectorNilUsesHelmValues: false