kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: c8-seperated-multi-node
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker  
- role: worker
  